# Generated by Django 4.2.6 on 2023-10-14 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
