# Generated by Django 4.2.6 on 2023-10-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcatalog_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcatalog',
            unique_together={('product', 'price')},
        ),
    ]
